# ============================================================================
# AUTHOR_ROOM REPOSITORY
# ============================================================================
# This file was auto-generated on: 2026-02-17 12:26:27 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD.
# OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from typing import List, Optional

from fastapi import HTTPException, status

from core.database import client
from schemas.author_room import AuthorRoomCreate, AuthorRoomOut, AuthorRoomUpdate


AUTHOR_ROOMS = "author_rooms"


async def create_author_room(
    author_room_data: AuthorRoomCreate,
) -> AuthorRoomOut:
    created = await client.insert_and_fetch(
        AUTHOR_ROOMS, author_room_data.model_dump()
    )
    assert created is not None
    return AuthorRoomOut(**created)


async def get_author_room(filter_dict: dict) -> Optional[AuthorRoomOut]:
    try:
        result = await client.find_one(AUTHOR_ROOMS, filter_dict)
        if result is None:
            return None
        return AuthorRoomOut(**result)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching author_room: {str(e)}",
        )


async def get_author_rooms(
    filter_dict: dict | None = None, start: int = 0, stop: int = 100
) -> List[AuthorRoomOut]:
    try:
        docs = await client.find_many(
            AUTHOR_ROOMS, filter_dict or {}, skip=start, limit=stop - start
        )
        return [AuthorRoomOut(**doc) for doc in docs]
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching author_rooms: {str(e)}",
        )


async def count_author_rooms(filter_dict: dict | None = None) -> int:
    return await client.count(AUTHOR_ROOMS, filter_dict or {})


async def update_author_room(
    filter_dict: dict, author_room_data: AuthorRoomUpdate
) -> AuthorRoomOut:
    result = await client.find_one_and_update(
        AUTHOR_ROOMS,
        filter_dict,
        {"set": author_room_data.model_dump(exclude_none=True)},
    )
    assert result is not None
    return AuthorRoomOut(**result)


async def delete_author_room(filter_dict: dict):
    return await client.delete_one(AUTHOR_ROOMS, filter_dict)
