# ============================================================================
# AUTHOR_ROOM REPOSITORY
# ============================================================================
# This file was auto-generated on: 2026-02-17 12:26:27 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.author_room import AuthorRoomUpdate, AuthorRoomCreate, AuthorRoomOut

async def create_author_room(author_room_data: AuthorRoomCreate) -> AuthorRoomOut:
    author_room_dict = author_room_data.model_dump()
    result =await db.author_rooms.insert_one(author_room_dict)
    result = await db.author_rooms.find_one(filter={"_id":result.inserted_id})
    returnable_result = AuthorRoomOut(**result)
    return returnable_result

async def get_author_room(filter_dict: dict) -> Optional[AuthorRoomOut]:
    try:
        result = await db.author_rooms.find_one(filter_dict)

        if result is None:
            return None

        return AuthorRoomOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching author_room: {str(e)}"
        )
    
async def get_author_rooms(filter_dict: dict = {},start=0,stop=100) -> List[AuthorRoomOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.author_rooms.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        author_room_list = []

        async for doc in cursor:
            author_room_list.append(AuthorRoomOut(**doc))

        return author_room_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching author_rooms: {str(e)}"
        )


async def count_author_rooms(filter_dict: dict | None = None) -> int:
    if filter_dict is None:
        filter_dict = {}
    return await db.author_rooms.count_documents(filter_dict)


async def update_author_room(filter_dict: dict, author_room_data: AuthorRoomUpdate) -> AuthorRoomOut:
    result = await db.author_rooms.find_one_and_update(
        filter_dict,
        {"$set": author_room_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = AuthorRoomOut(**result)
    return returnable_result

async def delete_author_room(filter_dict: dict):
    return await db.author_rooms.delete_one(filter_dict)
