# ============================================================================
# REACTION REPOSITORY
# ============================================================================
# This file was auto-generated on: 2026-02-17 19:06:49 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD.
# OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

import asyncio
from typing import Dict, List, Optional

from fastapi import HTTPException, status
from pymongo.errors import DuplicateKeyError

from core.database import ASC, client
from schemas.reaction import ReactionCreate, ReactionOut, ReactionUpdate


REACTIONS = "reactions"


_reaction_indexes_ready = False
_reaction_indexes_lock = asyncio.Lock()


async def ensure_reaction_indexes() -> None:
    global _reaction_indexes_ready
    if _reaction_indexes_ready:
        return

    async with _reaction_indexes_lock:
        if _reaction_indexes_ready:
            return
        await client.ensure_index(
            REACTIONS,
            [("userId", ASC), ("authorRoomId", ASC)],
            unique=True,
            background=True,
        )
        _reaction_indexes_ready = True


async def create_reaction(reaction_data: ReactionCreate) -> ReactionOut:
    await ensure_reaction_indexes()
    reaction_dict = reaction_data.model_dump()
    try:
        inserted_id = await client.insert_one(REACTIONS, reaction_dict)
    except DuplicateKeyError as err:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail="You have already reacted to this author room",
        ) from err
    created = await client.find_one(REACTIONS, {"_id": inserted_id})
    assert created is not None
    return ReactionOut(**created)


async def get_reaction(filter_dict: dict) -> Optional[ReactionOut]:
    try:
        result = await client.find_one(REACTIONS, filter_dict)
        if result is None:
            return None
        return ReactionOut(**result)
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching reaction: {str(e)}",
        )


async def get_reactions(
    filter_dict: dict | None = None, start: int = 0, stop: int = 100
) -> List[ReactionOut]:
    try:
        docs = await client.find_many(
            REACTIONS, filter_dict or {}, skip=start, limit=stop - start
        )
        return [ReactionOut(**doc) for doc in docs]
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching reactions: {str(e)}",
        )


async def count_reactions(filter_dict: dict | None = None) -> int:
    return await client.count(REACTIONS, filter_dict or {})


async def update_reaction(
    filter_dict: dict, reaction_data: ReactionUpdate
) -> ReactionOut:
    result = await client.find_one_and_update(
        REACTIONS,
        filter_dict,
        {"set": reaction_data.model_dump(exclude_none=True)},
    )
    assert result is not None
    return ReactionOut(**result)


async def delete_reaction(filter_dict: dict):
    return await client.delete_one(REACTIONS, filter_dict)


async def get_reaction_by_user_and_room(
    user_id: str, author_room_id: str
) -> Optional[ReactionOut]:
    return await get_reaction({"userId": user_id, "authorRoomId": author_room_id})


async def get_reactions_by_user_for_author_room_ids(
    user_id: str,
    author_room_ids: List[str],
) -> Dict[str, ReactionOut]:
    if not author_room_ids:
        return {}
    docs = await client.find_many(
        REACTIONS,
        {"userId": user_id, "authorRoomId": {"$in": author_room_ids}},
    )
    reaction_map: Dict[str, ReactionOut] = {}
    for doc in docs:
        reaction = ReactionOut(**doc)
        reaction_map[reaction.authorRoomId] = reaction
    return reaction_map


async def get_reaction_summary_by_author_room_id(
    author_room_id: str,
) -> Dict[str, int]:
    pipeline = [
        {"$match": {"authorRoomId": author_room_id}},
        {"$match": {"reaction": {"$type": "string", "$ne": ""}}},
        {"$group": {"_id": "$reaction", "count": {"$sum": 1}}},
    ]
    result = await client.aggregate(REACTIONS, pipeline)
    return {
        str(row["_id"]): int(row["count"])
        for row in result
        if row.get("_id") is not None
    }


async def get_reaction_summaries_for_author_room_ids(
    author_room_ids: List[str],
) -> Dict[str, Dict[str, int]]:
    if not author_room_ids:
        return {}

    pipeline = [
        {"$match": {"authorRoomId": {"$in": author_room_ids}}},
        {"$match": {"reaction": {"$type": "string", "$ne": ""}}},
        {
            "$group": {
                "_id": {
                    "authorRoomId": "$authorRoomId",
                    "reaction": "$reaction",
                },
                "count": {"$sum": 1},
            }
        },
    ]
    rows = await client.aggregate(REACTIONS, pipeline)
    summary_map: Dict[str, Dict[str, int]] = {}
    for row in rows:
        key = row.get("_id", {})
        author_room_id = key.get("authorRoomId")
        reaction = key.get("reaction")
        if author_room_id is None or reaction is None:
            continue
        summary_map.setdefault(str(author_room_id), {})[str(reaction)] = int(
            row.get("count", 0)
        )
    return summary_map
