# ============================================================================
# REACTION REPOSITORY
# ============================================================================
# This file was auto-generated on: 2026-02-17 19:06:49 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.reaction import ReactionUpdate, ReactionCreate, ReactionOut

async def create_reaction(reaction_data: ReactionCreate) -> ReactionOut:
    reaction_dict = reaction_data.model_dump()
    result =await db.reactions.insert_one(reaction_dict)
    result = await db.reactions.find_one(filter={"_id":result.inserted_id})
    returnable_result = ReactionOut(**result)
    return returnable_result

async def get_reaction(filter_dict: dict) -> Optional[ReactionOut]:
    try:
        result = await db.reactions.find_one(filter_dict)

        if result is None:
            return None

        return ReactionOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching reaction: {str(e)}"
        )
    
async def get_reactions(filter_dict: dict = {},start=0,stop=100) -> List[ReactionOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.reactions.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        reaction_list = []

        async for doc in cursor:
            reaction_list.append(ReactionOut(**doc))

        return reaction_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching reactions: {str(e)}"
        )


async def count_reactions(filter_dict: dict | None = None) -> int:
    if filter_dict is None:
        filter_dict = {}
    return await db.reactions.count_documents(filter_dict)


async def update_reaction(filter_dict: dict, reaction_data: ReactionUpdate) -> ReactionOut:
    result = await db.reactions.find_one_and_update(
        filter_dict,
        {"$set": reaction_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = ReactionOut(**result)
    return returnable_result

async def delete_reaction(filter_dict: dict):
    return await db.reactions.delete_one(filter_dict)
